### ISSUE TITLE
Erro ao executar o npm start

### ISSUE THREAD

**Issue by feliberal** [NandoMB/angular-veasy-table#1]
Boa tarde Fernando,
Estou tentando testar seu componente, mas ao executar o "npm start" ocorre o seguinte erro:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angular-veasy-table@1.5.8
6 info start angular-veasy-table@1.5.8
7 verbose unsafe-perm in lifecycle true
8 info angular-veasy-table@1.5.8 Failed to exec start script
9 verbose stack Error: angular-veasy-table@1.5.8 start: `node_modules/http-server/bin/http-server -c-1 -a localhost -p 3000`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid angular-veasy-table@1.5.8
11 verbose cwd C:\teste-veasytable\bower_components\angular-veasy-table
12 error Windows_NT 6.3.9600
13 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
14 error node v0.12.4
15 error npm  v2.10.1
16 error code ELIFECYCLE
17 error angular-veasy-table@1.5.8 start: `node_modules/http-server/bin/http-server -c-1 -a localhost -p 3000`
17 error Exit status 1
18 error Failed at the angular-veasy-table@1.5.8 start script 'node_modules/http-server/bin/http-server -c-1 -a localhost -p 3000'.
18 error This is most likely a problem with the angular-veasy-table package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node_modules/http-server/bin/http-server -c-1 -a localhost -p 3000
18 error You can get their info via:
18 error     npm owner ls angular-veasy-table
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Sabe me dizer o que pode estar acontecendo?

**Comment by NandoMB** [comment]
Boa tarde amigo,

Posso estar enganado, mas me parece que você não instalou o npm...

Para rodar a demonstração, você precisa primeiro ter o grunt e o bower instalados globalmente (com -g).
Depois disso, você precisa rodar dois comandos:

``` js
npm install;
```

``` js
bower install;
```

Após instalar as dependências do projeto, você pode testar o projeto rodando o comando:

``` js
npm start;
```

**Comment by feliberal** [comment]
Obrigado pela ajuda... 

Eu consegui resolver meu problema instalando o npm http-server via:

`$ npm install http-server -g`

`$ http-server -a localhost -p 3000`

Uma dúvida, como eu não tenho muito conhecimento do github, a pasta bower_components gerada através do `$ bower install` não deveria estar dentro da pasta demo para que os exemplos funcionem perfeitamente?

**Comment by NandoMB** [comment]
Olá amigo,

Na realidade, não tem nada a ver com o GitHub e sim com o bower.
A pasta 'bower_components' é gerada quando você roda o comando "bower
install". Você pode olhar o arquivo ".bowerrc", la dentro eu digo para o
bower, instalar as dependências dentro da pasta "demo/bower_components".

O local aonde ela (bower_components) vai ficar é indiferente, desde que
você mantenha as referências corretas para o local.

Um abraço
